apiVersion: v1
kind: Service
metadata:
  name: flask-service
  labels:
    app: flask
spec:
  type: {{ .Values.service.type }}
  selector:
    app: flask
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.flask.targetPort }}
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: 30080
      {{- end }}
